name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

    steps:
      - name: Say Hello
        run: echo "👋 Hello! This is your first GitHub Action."

      - name: Print Current Date & Time
        run: date
